# Generated by Django 5.0.7 on 2024-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='resume',
            field=models.FileField(upload_to='resumes'),
        ),
    ]
