# Generated by Django 5.0.7 on 2024-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_resumes_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='created_at_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
